/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: endpoint.i

package swig

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
typedef _gostring_ swig_type_3;
extern void _wrap_Swig_free_swig_17e9e0cf162c90a9(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_swig_17e9e0cf162c90a9(swig_intgo arg1);
extern void _wrap_Endpoint_str_set_swig_17e9e0cf162c90a9(uintptr_t arg1, swig_type_1 arg2);
extern swig_type_2 _wrap_Endpoint_str_get_swig_17e9e0cf162c90a9(uintptr_t arg1);
extern swig_type_3 _wrap_Endpoint_hash_swig_17e9e0cf162c90a9(uintptr_t arg1);
extern uintptr_t _wrap_new_Endpoint_swig_17e9e0cf162c90a9(void);
extern void _wrap_delete_Endpoint_swig_17e9e0cf162c90a9(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_swig_17e9e0cf162c90a9(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_swig_17e9e0cf162c90a9(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrEndpoint uintptr

func (p SwigcptrEndpoint) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrEndpoint) SwigIsEndpoint() {
}

func (arg1 SwigcptrEndpoint) SetStr(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Endpoint_str_set_swig_17e9e0cf162c90a9(C.uintptr_t(_swig_i_0), *(*C.swig_type_1)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrEndpoint) GetStr() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Endpoint_str_get_swig_17e9e0cf162c90a9(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrEndpoint) Hash() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Endpoint_hash_swig_17e9e0cf162c90a9(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func NewEndpoint() (_swig_ret Endpoint) {
	var swig_r Endpoint
	swig_r = (Endpoint)(SwigcptrEndpoint(C._wrap_new_Endpoint_swig_17e9e0cf162c90a9()))
	return swig_r
}

func DeleteEndpoint(arg1 Endpoint) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Endpoint_swig_17e9e0cf162c90a9(C.uintptr_t(_swig_i_0))
}

type Endpoint interface {
	Swigcptr() uintptr
	SwigIsEndpoint()
	SetStr(arg2 string)
	GetStr() (_swig_ret string)
	Hash() (_swig_ret string)
}


